#! /bin/bash
# this script self-destructs the gbfix utility

read -n 1 -p "WARNING - you are about to remove the GB repair utility, proceed? (Y/n): " YesNo
echo
if [[ "$YesNo" = "Y" ]]; then
  rm -f gbfix
  echo "The GB repair script utility has been successfully deleted."
fi
