#! /bin/bash

echo "Stopping the admin service...."
sudo /batm/batm-manage stop admin
sleep 30
STANDALONE_XML="/batm/app/admin/standalone/configuration/standalone.xml"
sed -i 's/autoReconnect=true<\/connection-url>/autoReconnect=true\&amp;useCursorFetch=true<\/connection-url>/' "$STANDALONE_XML"
echo "Starting the admin service..."
sudo /batm/batm-manage start admin
sleep 30
echo "Completed. Please check your site now."
